import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Products from "./store";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });



export default function Home({data}) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hi, Next</h1>
      
      
      <Link href="/store">All Products</Link>
    </>
  );
}
